### ISSUE TITLE
ERROR 500

### ISSUE THREAD

**Issue by lingrlongr** [saxix/django-webcam#1]
I finally got this working.  Using Chrome (21.0.1180.89 m) I'm able to save snapshot images, but when using IE (v8) or Firefox (), the images don't seem to save (the camera works though in the browser window though).  

In Chrome's console, it's logging errors:
POST http://example.com/picture/1/ 500 (INTERNAL SERVER ERROR) jquery.min.js:16
d.support.ajax.d.ajaxTransport.send jquery.min.js:16
d.extend.ajax jquery.min.js:16
d.each.d.(anonymous function) jquery.min.js:16
saveCB /medapp/camera/:67
$.webcam.onSave /medapp/camera/:93
(anonymous function)
$.fn.webcam.webcam.save jquery.webcam.js:75
$.webcam.onCapture /medapp/camera/:96
(anonymous function)
$.fn.webcam.webcam.capture jquery.webcam.js:69
(anonymous function) /medapp/camera/:104
d.event.handle jquery.min.js:16
d.event.add.k.handle.m

In Firefox's error console, it's logging errors:
[12:48:10.971] TypeError: webcam.capture is not a function @ camera:104

In IE, I can't see any errors.

Any ideas?  I don't know how I could debug that 500 error...

**Comment by saxix** [comment]
Hi please check last version. Totally removed ajax call that required the record to be saved before make valid snapshots. Now you  can save as file or as db field. Also added working demo

**Comment by lingrlongr** [comment]
nice!  i see lots of commits.  :)  i messed around with my last checkout to try to get it all working for me.  I'll have to give the changes a try.
